### PR TITLE
Add LUT and invert intensity feature

### PR DESCRIPTION
**Pull request by pwalczysko**
Add LUT and invert intensity features to iviewer guide.

This is to make the link from the New features https://www.openmicroscopy.org/omero/features/ on www to point to a sensible workflow, see https://github.com/ome/www.openmicroscopy.org/pull/396

cc @jburel

### CODE REVIEW

**Review by manics — COMMENTED** [review]
Changes look fine.

In the last step
> Go back to OMERO.iviewer, click on the Settings tab and adjust the channel names:

Should this be go back to the webclient? Iviewer doesn't let you edit the channel names.
image

**Comment by pwalczysko** [comment]
> Iviewer doesn't let you edit the channel names.

good point&catch - thank you @manics

**Comment by pwalczysko** [comment]
Fixed - moved the channel renaming feature to the data management in https://github.com/ome/omero-guide-introduction/pull/9

**Review by manics — APPROVED** [review]
LGTM

**Comment by pwalczysko** [comment]
Thank you @manics 

Merging

**Comment by jburel** [comment]
Late comment: maybe indicate that we support all the LUTs from IJ

**Comment by pwalczysko** [comment]
> Late comment: maybe indicate that we support all the LUTs from IJ

Suggested fix in https://github.com/ome/omero-guide-iviewer/pull/7

**Pull request merged**
